spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_project?useSSL=true&serverTimezone=UTC
    username: root
    password: 19980125
  jpa:
    show-sql: false
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8